import React, { useState } from "react";
import { DocItem } from "../types";
import { FileText, BookOpen, Key, AlertCircle, RefreshCw, Check, Copy } from "lucide-react";

interface DocumentationModuleProps {
  docs: DocItem[];
  repositoryName: string;
}

export default function DocumentationModule({ docs, repositoryName }: DocumentationModuleProps) {
  const [activeTab, setActiveTab] = useState<string>(docs[0]?.category || "readme");
  const [loading, setLoading] = useState(false);
  const [customDocs, setCustomDocs] = useState<Record<string, string>>({});
  const [copied, setCopied] = useState(false);

  // Filter docs based on current category tab selection
  const activeDoc = docs.find((d) => d.category === activeTab);
  const displayContent = customDocs[activeTab] || activeDoc?.content || `# No custom content generated yet.\nClick "AI Re-generate" to populate this segment with deep system reviews.`;

  const handleRegenerate = async () => {
    setLoading(true);
    try {
      const response = await fetch("/api/doc/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          category: activeTab,
          repositoryName,
        }),
      });

      if (!response.ok) throw new Error("Documentation generation failed");
      const data = await response.json();
      setCustomDocs((prev) => ({
        ...prev,
        [activeTab]: data.content,
      }));
    } catch (err) {
      console.warn(err);
      // fallback
      setCustomDocs((prev) => ({
        ...prev,
        [activeTab]: `# Refactored: AI Senior Architect Review of ${repositoryName}\n\n1. Enforce secure container parameters.\n2. Ensure zero-trust database query networks.\n3. Fully unit-tested files inside routing pipelines.`,
      }));
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(displayContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  return (
    <div className="space-y-6 font-sans">
      {/* Banner */}
      <div className="bg-white p-6 rounded-2xl border border-slate-100 shadow-xs flex flex-col md:flex-row items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="p-3 bg-blue-50 text-blue-600 rounded-xl">
            <BookOpen className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-slate-800">DocCenter Autogeneration</h2>
            <p className="text-sm text-slate-500 mt-0.5 max-w-2xl">
              Understand logic, setups, and integration APIs instantly. Senior engineer-level autogenerated developer guides and setup manuals.
            </p>
          </div>
        </div>

        <button
          onClick={handleRegenerate}
          disabled={loading}
          className="flex items-center justify-center gap-2 px-4.5 py-2 hover:bg-slate-50 border border-slate-200 text-slate-700 text-sm font-semibold rounded-xl disabled:opacity-45 cursor-pointer active:scale-98 transition-all"
        >
          {loading ? (
            <>
              <RefreshCw className="w-4 h-4 animate-spin" />
              Expanding Docs...
            </>
          ) : (
            <>
              <RefreshCw className="w-4 h-4" />
              AI Expand Segment
            </>
          )}
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        {/* Navigation panel */}
        <div className="lg:col-span-1 bg-white p-4 rounded-2xl border border-slate-100 shadow-xs space-y-1">
          <h3 className="text-2xs font-black text-slate-400 uppercase tracking-widest pl-2 mb-3">Doc Segments</h3>
          {[
            { id: "readme", label: "Overview & Features", icon: FileText },
            { id: "api", label: "REST Endpoint Reference", icon: BookOpen },
            { id: "setup", label: "Local Developer Guide", icon: Key },
          ].map((item) => {
            const Icon = item.icon;
            return (
              <button
                key={item.id}
                onClick={() => setActiveTab(item.id)}
                className={`flex items-center gap-2.5 w-full text-left px-3.5 py-3 rounded-xl text-xs font-semibold transition-all cursor-pointer ${
                  activeTab === item.id
                    ? "bg-blue-50 text-blue-700 border-l-4 border-blue-600 font-extrabold"
                    : "text-slate-500 hover:bg-slate-50 hover:text-slate-700"
                }`}
              >
                <Icon className="w-4 h-4 shrink-0" />
                <span>{item.label}</span>
              </button>
            );
          })}
        </div>

        {/* Markdown Content Viewer */}
        <div className="lg:col-span-3 bg-white p-6 md:p-8 rounded-2xl border border-slate-100 shadow-sm relative">
          <div className="absolute top-4 right-4 flex items-center">
            <button
              onClick={handleCopy}
              className="p-2 text-slate-400 hover:text-slate-600 rounded-lg bg-slate-50 border border-slate-200 hover:bg-slate-100 cursor-pointer flex items-center justify-center gap-1.5 text-xs font-bold transition-all"
            >
              {copied ? (
                <>
                  <Check className="w-3.5 h-3.5 text-emerald-500 hover:text-emerald-500" />
                  Copied
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" />
                  Copy Markdown
                </>
              )}
            </button>
          </div>

          <div className="prose prose-slate max-w-none text-slate-800 leading-relaxed font-sans mt-2">
            <div className="whitespace-pre-wrap select-text markdown-body text-xs font-mono bg-slate-50/50 p-6 rounded-xl border border-slate-100 leading-relaxed">
              {displayContent}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
